// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3C1tKswE31TMRZwcAZ6NcS_K_848i3jM',
    appId: '1:575202228925:web:b325062897fe9ffab095d4',
    messagingSenderId: '575202228925',
    projectId: 'aamtspn-41828',
    authDomain: 'aamtspn-41828.firebaseapp.com',
    storageBucket: 'aamtspn-41828.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNiw3tam6iCYbX1nELkICyja_QIY3TdV8',
    appId: '1:575202228925:android:e24ebdaa9484c6d7b095d4',
    messagingSenderId: '575202228925',
    projectId: 'aamtspn-41828',
    storageBucket: 'aamtspn-41828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB575dNSOjnHOPFeFkWbop7qhLkf-w_lhE',
    appId: '1:575202228925:ios:d6baf1cf7a5f6a53b095d4',
    messagingSenderId: '575202228925',
    projectId: 'aamtspn-41828',
    storageBucket: 'aamtspn-41828.appspot.com',
    iosClientId: '575202228925-pe8rg8ul2tk5b297rmsgt1olsq93qj0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB575dNSOjnHOPFeFkWbop7qhLkf-w_lhE',
    appId: '1:575202228925:ios:d6baf1cf7a5f6a53b095d4',
    messagingSenderId: '575202228925',
    projectId: 'aamtspn-41828',
    storageBucket: 'aamtspn-41828.appspot.com',
    iosClientId: '575202228925-pe8rg8ul2tk5b297rmsgt1olsq93qj0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
